# Generated by Django 2.1.2 on 2018-10-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LfasrModel',
            fields=[
                ('md5', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, max_length=1024, null=True)),
                ('step', models.CharField(choices=[('upload', '上传'), ('processing', '处理中'), ('finish', '完成')], max_length=32)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('desc', models.CharField(max_length=1024)),
            ],
        ),
    ]
