# Generated by Django 2.1.2 on 2018-10-16 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BatchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LfasrModel',
            fields=[
                ('md5', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=1024, null=True)),
                ('task_id', models.CharField(blank=True, max_length=256, null=True)),
                ('step', models.CharField(choices=[('upload', '上传'), ('processing', '处理中'), ('finish', '完成')], max_length=32)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=1024, null=True)),
                ('data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailModel',
            fields=[
                ('message_id', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('mailfrom', models.CharField(blank=True, max_length=1024, null=True)),
                ('subject', models.CharField(blank=True, max_length=1024, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='batchmodel',
            name='mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.MailModel'),
        ),
        migrations.AddField(
            model_name='batchitemmodel',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.BatchModel'),
        ),
        migrations.AddField(
            model_name='batchitemmodel',
            name='lfasr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.LfasrModel'),
        ),
    ]
