# Generated by Django 2.1.2 on 2018-10-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchitemmodel',
            name='filename',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
