# Generated by Django 2.1.2 on 2018-10-12 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LfasrModel',
            new_name='LfasrModel1',
        ),
    ]
