# Generated by Django 2.1.2 on 2018-10-12 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20181012_0147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LfasrModel1',
            new_name='LfasrModel',
        ),
    ]
