# Generated by Django 2.1.2 on 2018-10-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20181012_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='lfasrmodel',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
